### ISSUE TITLE
visionOS AppIcon

### ISSUE THREAD

**Issue by noppefoxwolf** [tryswift/trySwiftTokyoApp#25]
Related: https://github.com/tryswift/trySwiftTokyoApp/pull/24

In visionOS, AppIcon needs to have three layers.
https://developer.apple.com/documentation/xcode/configuring-your-app-icon

Currently AppIcon PSD file is not public. 
I wish you to add psd resource in repository or upload to any storage.

**Comment by d-date** [comment]
Hi @noppefoxwolf ,

You can use our materials under CC BY 4.0:
https://github.com/tryswift/riko

Enjoy

**Comment by noppefoxwolf** [comment]
Thank you so much!
