### ISSUE TITLE
individual sponsor accounts order is not same as Web.

### ISSUE THREAD

**Issue by noppefoxwolf** [tryswift/trySwiftTokyoApp#26]
|Web|App|
|---|---|
|![CleanShot 2024-03-14 at 00 15 35@2x](https://github.com/tryswift/trySwiftTokyoApp/assets/2066707/4d8d6c08-aa52-4a35-befd-d007f45af670)|![CleanShot 2024-03-14 at 00 15 30@2x](https://github.com/tryswift/trySwiftTokyoApp/assets/2066707/40f98bec-64bd-4211-a030-acb4a8753360)|

**Comment by d-date** [comment]
We don't plan to work on this issue since the order of individuals is not so important.
They are listed in descending order of the amount of support given.
